"""again fix relation problem

Revision ID: 593930aea021
Revises: 0847a5148feb
Create Date: 2024-10-09 19:00:43.942412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593930aea021'
down_revision: Union[str, None] = '0847a5148feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('tag_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'pictures', 'tags', ['tag_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_column('pictures', 'tag_name')
    # ### end Alembic commands ###
